### ISSUE TITLE
start up erro with crash

### ISSUE THREAD

**Issue by saliger84** [tenondra/eods#2]
when lunching the game i get
  ( file eods_ieds\config.cpp line 1349   
'/cfgVehicles/EODS_ieds01_armed ':'+' encountered instead of '='

**Comment by tenondra** [comment]
should be fixed in next update

**Comment by saliger84** [comment]
also seams that the server key doesnt work on a dedicated server keeps tellling me i need to remove the mod to play mission

**Comment by saliger84** [comment]
if needed i do have a dedicated server that we can test this mod on its only a 4 person server just let me know and ill set up the acsess to the FTP and we can get on teamspeak or discord which ever would work best i do have xperence with blender  and photoshop willing to help as much as possible

**Comment by tenondra** [comment]
Check it now, if that error is still present. About the bikey - i know, I will include it.. the mods still kinds mess since the state Katie has left it in isn't the same as latest stable eods release. And - thanks for your support, we've got our own dedi where we can test stuff. Your blender skills might be useful in the future, cheers (:

**Comment by tenondra** [comment]
please. reopen if not fixed
